### ISSUE TITLE
Rack::ShowExceptions must be displayed for real deployment.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/discoverycenter#17]
Rack::ShowExceptions is current enabled so if site breaks it shows exception and requests details which may show sensitive information. Need to make sure this is disabled for final deployment.

**Comment by thoraxe** [comment]
@developercorey

**Comment by coreydaley** [comment]
We can look into this, but it's a static html site, not sure what sensitive information could possibly be displayed that isn't already public anyways.

**Comment by coreydaley** [comment]
Closing due to age
