### ISSUE TITLE
README should indicate how to get Middleman installed/running/etc

### ISSUE THREAD

**Issue by thoraxe** [openshift/discoverycenter#8]

**Comment by ryanj** [comment]
@thoraxe: could I get the basic list of commands to install deps, and boot the server?

I'll fill out the rest of the README

**Comment by ryanj** [comment]
I'll link to the styleguide from the "Contributing" section: http://discover.openshift.com/samples/styleguide.html

**Comment by ryanj** [comment]
old devcenter "getting started" info: https://github.com/openshift/devcenter
